### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by chrisdevcl** [whallysson/netbeans-11-macos-bundle#1]
I´ve been trying to install with the command line ./install.sh but i can't do it.
![Captura de Pantalla 2019-06-11 a la(s) 20 55 51](https://user-images.githubusercontent.com/41346813/59316235-62f3d300-8c8b-11e9-8d06-bb2bbdf8893c.png)

**Comment by whallysson** [comment]
It looks like user permission. There is many way to execute your script:
- launch bash with root privilege:
`sudo bash install.sh`
or
- change permissions to launch the script. You must probably run it as root:
`chmod +x install.sh or chmod 755 install.sh`

**Comment by chrisdevcl** [comment]
Thanks for your answer, I was able to do with sudo bash install.sh
